"""add upload storage and summary metrics

Revision ID: 0539ac7c9ad1
Revises: 97b56d461f28
Create Date: 2026-03-06 14:22:42.563140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0539ac7c9ad1'
down_revision = '97b56d461f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('unique_source_ips', sa.Integer(), server_default='0', nullable=False)
        )
        batch_op.add_column(
            sa.Column('top_categories', sa.JSON(), server_default='[]', nullable=False)
        )
        batch_op.add_column(
            sa.Column('top_destinations', sa.JSON(), server_default='[]', nullable=False)
        )
        batch_op.add_column(
            sa.Column('top_source_ips', sa.JSON(), server_default='[]', nullable=False)
        )

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('top_source_ips')
        batch_op.drop_column('top_destinations')
        batch_op.drop_column('top_categories')
        batch_op.drop_column('unique_source_ips')

    # ### end Alembic commands ###
